postprocessor:
  name: t2fnorm
  APS_mode: True
  postprocessor_args:
    percentile: 85
    tau: 0.1
  postprocessor_sweep:
    percentile_list: [65, 70, 75, 80, 85, 90, 95]
    tau_list: [0.0001, 0.001, 0.01, 0.1, 1]
